---
- name: Install and configure XRDP on Ubuntu 20.04
  hosts: localhost
  connection: local
  become: yes  # Ensures root privileges
  vars:
    hwe_suffix: ""  # Change to "-hwe-20.04" if HWE kernel is required

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Fail if reboot is required
      fail:
        msg: "A reboot is required to proceed with the installation. Please reboot and rerun this playbook."
      when: reboot_required.stat.exists

    - name: Install necessary utilities
      apt:
        name:
          - "linux-tools-virtual{{ hwe_suffix }}"
          - "linux-cloud-tools-virtual{{ hwe_suffix }}"
        state: present

    - name: Install XRDP
      apt:
        name: xrdp
        state: present

    - name: Stop XRDP services before configuration
      systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - xrdp
        - xrdp-sesman

    - name: Configure XRDP ini files
      lineinfile:
        path: "/etc/xrdp/xrdp.ini"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: yes
      loop:
        - { regexp: '^port=3389', line: 'port=vsock://-1:3389' }
        - { regexp: '^security_layer=negotiate', line: 'security_layer=rdp' }
        - { regexp: '^crypt_level=high', line: 'crypt_level=none' }
        - { regexp: '^bitmap_compression=true', line: 'bitmap_compression=false' }

    - name: Create startubuntu.sh if it doesn't exist
      blockinfile:
        path: /etc/xrdp/startubuntu.sh
        create: yes
        marker: ""
        block: |
          #!/bin/sh
          export GNOME_SHELL_SESSION_MODE=ubuntu
          export XDG_CURRENT_DESKTOP=ubuntu:GNOME
          exec /etc/xrdp/startwm.sh
      mode: '0755'

    - name: Use the startubuntu script for session management
      lineinfile:
        path: /etc/xrdp/sesman.ini
        regexp: '^startwm='
        line: 'startwm=startubuntu'
        backup: yes

    - name: Rename redirected drives to 'shared-drives'
      lineinfile:
        path: /etc/xrdp/sesman.ini
        regexp: '^FuseMountName=thinclient_drives'
        line: 'FuseMountName=shared-drives'
        backup: yes

    - name: Allow any user to start an X session
      lineinfile:
        path: /etc/X11/Xwrapper.config
        regexp: '^allowed_users=console'
        line: 'allowed_users=anybody'
        backup: yes

    - name: Blacklist vmw_vsock_vmci_transport module
      copy:
        dest: /etc/modprobe.d/blacklist-vmw_vsock_vmci_transport.conf
        content: "blacklist vmw_vsock_vmci_transport"
        mode: '0644'

    - name: Ensure hv_sock gets loaded at boot
      copy:
        dest: /etc/modules-load.d/hv_sock.conf
        content: "hv_sock"
        mode: '0644'

    - name: Configure policy for XRDP session
      copy:
        dest: /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
        content: |
          [Allow Colord all Users]
          Identity=unix-user:*
          Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
          ResultAny=no
          ResultInactive=no
          ResultActive=yes
        mode: '0644'

    - name: Reload systemd daemon and start XRDP
      systemd:
        daemon_reload: yes
        name: xrdp
        state: started
        enabled: yes

    - name: Notify the user of installation completion
      debug:
        msg: "Install is complete. Reboot your machine to begin using XRDP."
